### ISSUE TITLE
In high-dimensional tasks, does the root node still represent the entire search space?

### ISSUE THREAD

**Issue by tjdeng** [facebookresearch/LaMCTS#15]
Hi,

For example, the search space size of NASNet is 3.5x10^21. it is [3.5x10^21, 160] after encoding all arch to masks. this array is quite huge, so it can not work on my device. so how do you deal with it?

Thanks in advance!

**Comment by linnanwang** [comment]
I think the answer is pretty straightforward, and all you need is to re-write my code to use a sampler. By the time I developed the distributed NAS, I only had 3 weeks to perform searching and training. So I chose to do an engineering simplification by evenly sampling a lot of networks using MCMC sampler, then choose one from them. Apparently, this is not desired, and you can rewrite that part to use some random sampler, and it should not be hard to change so.

**Comment by tjdeng** [comment]
Thank you for your reply.

What you mean is to sample a subspace from the entire search space, and perform searching and training based on this subspace all the time, right?

**Comment by linnanwang** [comment]
That's my engineering simplification used under a looming deadline.

You should use a random sampler instead, e.g. hit and run sampler. You shall revise the code to have that function implemented.

**Comment by linnanwang** [comment]
In fact, I just recall, you can use one-shot LaNAS and it has the sampler implemented. So, that does not have the engineering simplification mentioned above.

Check the code here: https://github.com/facebookresearch/LaMCTS/tree/master/LaNAS/one-shot_LaNAS

**Comment by linnanwang** [comment]
close for issue being resolved.
