### ISSUE TITLE
Are there any other ways to get the CIFAR10 pre-trained checkpoint?

### ISSUE THREAD

**Issue by Ema1997** [facebookresearch/LaMCTS#16]
Hi,
When I tried to download the pre-trained checkpoint `lanas_128_99.03.zip` from the url `https://drive.google.com/file/d/1bZsEoG-sroVyYR4F_2ozGLA5W50CT84P/view?usp=sharing` you provided, I failed. Therefore, are there any other ways to get the pre-trained checkpoint?

**Comment by linnanwang** [comment]
Hello, 

Are you located in mainland China? Please use VPN, and I double-checked the checkpoint is okay to download.
