### ISSUE TITLE
Genetic algorithm

### ISSUE THREAD

**Issue by nikky4D** [facebookresearch/LaMCTS#2]
I would like to test it out for genetic algorithm. But I'm not sure where the fitness function, or the parent selection function would go. Would you have a demo that perharps applies this?

**Comment by linnanwang** [comment]
It is hard for me to understand what you want to do given your description. Are you trying to use LA-MCTS to find a good partition to improve Genetic Algorithms? Or are you just want to evaluate GA against LA-MCTS? thank you.

**Comment by nikky4D** [comment]
Thanks for the reply. I'm curious to see if LaMCTS can be applied for an image optimization problem. I have a genetic algorithm solver for puzzle reconstruction. I want to repurpose the entire solver as LAMCTS. But I'm not sure where the various functions will fit. Does this make sense?

**Comment by linnanwang** [comment]
I'd see that as applying LA-MCTS to optimize another function. Please take a look at these codes (https://github.com/facebookresearch/LaMCTS/blob/master/LA-MCTS/functions/functions.py), and we have separate the search and the function to be optimized. So, all you need is to write a function f, that takes some configuration x, and collect the performance metric f(x). Once you implemented f(x), all you need is to instantiate the function and pass it into LA-MCTS. take a look at run.py, everything shall be very straightforward.

So, my next question is, how many dimensions in your x? and what's the range of each dimensions?
