### ISSUE TITLE
Cannot reproduce the results of Ackley-20d in the paper

### ISSUE THREAD

**Issue by gloaming2dawn** [facebookresearch/LaMCTS#20]
Hi, thank you for your good work. 

Now I am trying to reproduce the results of Ackley-20d in the LAMCTS paper (Fig. 4). I use the same hyper-parameters as (cp=1, leaf size=20) and run:
cd LA-MCTS
python run.py --func ackley --dims 20 --iterations 1000

I have repeated the process for 20 times, however I cannot obtain the the results in the paper. Is there anything I need to change to reproduce the results?

**Comment by linnanwang** [comment]
What are the results you have got on your side? Sorry I just got noticed about this issue.

**Comment by gloaming2dawn** [comment]
> What are the results you have got on your side? Sorry I just got noticed about this issue.

I found the result of LAMCTS-BO (the base model is BO) is similar to naive BO.

**Comment by linnanwang** [comment]
Hello,

Can you please provide more data for me to analyze? E.g., what are the results on your side? Are you able to replicate Ackley-10d and see the difference? Thanks.

**Comment by gloaming2dawn** [comment]
Hi, thank you for your reply.  Just see the image below. All I did is to Open file LA-MCTS/run.py, change line 57 to leaf_size =20. Then run the following command:
python run.py --func ackley --dims 20 --iterations 1000

![image](https://user-images.githubusercontent.com/31033243/139868048-0b2cb6db-8ed8-44f5-803d-77576e63844d.png)

**Comment by gloaming2dawn** [comment]
As it is easy to repeat the process, could you please try to reproduce the results of Ackley-20d again using LAMCTS-BO from the current source code? I think there may be something wrong in the current code.

**Comment by linnanwang** [comment]
Thanks, Likely this is due to the configurations. I will look into this and get back to you later (after Nov-16th ;), a deadline for me).

**Comment by gloaming2dawn** [comment]
Hi, I have found why it failed. Just modify line 243 in MCTS.py, leaf.propose_samples_bo( 1, path, self.lb, self.ub, self.samples ) to leaf.propose_samples_bo( 10, path, self.lb, self.ub, self.samples )

**Comment by linnanwang** [comment]
Hello, 

I'm glad you figure it out. Can you leave your email? I will send you the codes to Ackley-20d for reproduction.

**Comment by gloaming2dawn** [comment]
Thank you. My email is jiayuzhao199567@163.com. Could you please also provide the codes of Half-Cheetah function and And function?

**Comment by linnanwang** [comment]
sent, the files also contain the original log.

**Comment by linnanwang** [comment]
Hey

Did you receive my codes? Have you resolved this issue? Thanks.
