### ISSUE TITLE
TuRBO experiment reproduction

### ISSUE THREAD

**Issue by yunyuewei** [facebookresearch/LaMCTS#25]
Hi, I want to reproduce the experiment using TuRBO. It seems that following the steps in [https://github.com/facebookresearch/LaMCTS/tree/main/LA-MCTS](https://github.com/facebookresearch/LaMCTS/tree/main/LA-MCTS) can not successfully run the commented code. I have some questions about current code.

1. Line 362 in [Classifier.py](https://github.com/facebookresearch/LaMCTS/blob/main/LA-MCTS/lamcts/Classifier.py). It seems that we need to input initial points into TuRBO agent. But the original TuRBO implementation does not support this customization.
2. In the paper, you mentioned that "we restrict the TuRBO to uniformly sample from the intersection of the bounding box and $\Omega_{selected}$ ". But I didn't find the implementation in current code. 

Could you give me some suggestions about TuRBO reproduction?

**Comment by yuandong-tian** [comment]
Did you follow README.md? There is a `revision.patch` file and you can simply apply that patch to enable TuRBO.

**Comment by yunyuewei** [comment]
Thanks! I think I missed this part when reading README.md. Now I can run the code after applying the patch.
