### ISSUE TITLE
A question on the readme.md

### ISSUE THREAD

**Issue by xvhuan** [facebookresearch/LaMCTS#30]
I found in the readme that the command `python train.py --auxiliary --batch_size=32 --init_ch=128 --**layer**=24` sets the parameter `**layer**` to 24. However, in the actual code, it should be specified as `**layers**` using `parser.add_argument('--**layers**', type=int, default=20, help='total number of layers')`. I am not sure if using 20 for `layers` can achieve an accuracy of 99.03%.

**Comment by linnanwang** [comment]
After a couple years later, I don't encourage you to chase 99% accuracy on CIFAR10. It is not a good metric in either judging a good search algorithm or something quite useful.

As for your question, sorry I completely forget the details now.
