### ISSUE TITLE
Why propose_samples_turbo is commented?

### ISSUE THREAD

**Issue by machanic** [facebookresearch/LaMCTS#4]
Why does not provide TurBO code in Classifier.py ?
I notice the method of `def propose_samples_turbo(self, num_samples, path, func)` in https://github.com/facebookresearch/LaMCTS/blob/master/LA-MCTS/Classifier.py#L343 is commented.

**Comment by linnanwang** [comment]
It will throw compilation error if TuRBO does not exists in the repo, however, including TuRBO will have legal issues. So, please follow the instructions here to use TuRBO. https://github.com/facebookresearch/LaMCTS/tree/master/LA-MCTS
