### ISSUE TITLE
关于search中函数值计算的一些问题

### ISSUE THREAD

**Issue by iceking112** [facebookresearch/LaMCTS#6]
我注意到在collect_samples function中对函数值是做了*-1，我的理解是想取到函数的最小值，但是为何在输出 best f(x)时使用np.absolute(curt_best_value)？

**Comment by linnanwang** [comment]
Free free to remove np.absolute. It simply matches the output of Nevergrad, etc. Otherwise, some may get confused by the negative sign here.
