### ISSUE TITLE
How long did it take the author to train the LaNet with 1000 EPOCH.

### ISSUE THREAD

**Issue by yifan123** [facebookresearch/LaMCTS#9]
The training speed on the V100 without using any tricks is about 0.23h/epoch, which is too slow.  If autoaug and ema are used, the speed will become more slowly.
So I would like to ask: how long did it take the author to train the LaNet with 1000 EPOCH.

**Comment by linnanwang** [comment]
Usually it takes us 4~6 days to train on cifar10 using 1GPU to finalize 600 epochs training. Why train 1000?

**Comment by yifan123** [comment]
![image](https://user-images.githubusercontent.com/37578514/103907939-e2ce7180-513c-11eb-8b00-d75745704700.png)
It seems that the latency of LANET is larger than that of the same FLOPS networks. It is rare to see a network requires 24 hours to train for 100 epochs on CIFAR10.

**Comment by linnanwang** [comment]
We dont care about latency in this case, but to reach the best accuracy.

**Comment by linnanwang** [comment]
oh you can use different epochs. In the paper, we ask to train to 600 epochs. But I will update this later.
